CREATE TABLE IF NOT EXISTS sales_data (
sale_date DATE NOT NULL, 
sale_id VARCHAR(50) PRIMARY KEY,
product_id VARCHAR(50) NOT NULL,
product_name VARCHAR(100) NOT NULL,
product_category VARCHAR(50) NOT NULL,
quantity_sold INTEGER NOT NULL,
unit_price FLOAT NOT NULL,
discount INTEGER,  
total_value FLOAT NOT NULL,
unit_cost FLOAT NOT NULL,
total_cost FLOAT NOT NULL,
gross_profit FLOAT NOT NULL,
payment_method VARCHAR(50) NOT NULL,
payment_status VARCHAR(50) NOT NULL,
payment_date DATE,  
customer_id VARCHAR(50) NOT NULL,
customer_name VARCHAR(100) NOT NULL,
sales_channel VARCHAR(50) NOT NULL,
sales_region VARCHAR(50) NOT NULL,
sales_rep VARCHAR(100) NOT NULL,
customer_rating VARCHAR(50),
shipping_cost FLOAT NOT NULL,
delivery_status VARCHAR(50) NOT NULL,
delivery_date DATE 
);